- testcases/virt_who/virtwhobase.py
if /etc/sysconfig/virt-who has been changed, esx_setup() => update_esx_vw_configure() will failed
if host was registered already for hyperV testing, esx_setup() => sub_isregistered() will skip to config the rhsm.conf, can't change hyperV settings to esx's
> update virtwhobase.py esx_setup(), need to clean esx host before setup

- testcases/rhsm/rhsm_gui/tc_ID115186_GUI_list_facts_info_of_curent_system_via_gui.py
- testcases/rhsm/rhsm_gui/tc_ID191583_GUI_filter_options_should_be_saved.py
- testcases/rhsm/rhsm_gui/tc_ID262134_GUI_launch_subscription_manager_gui_with_invalid_proxy_url.py
- testcases/rhsm/rhsm_gui/tc_ID262212_GUI_subscription_manager_gui_live_filter_should_not_crash.py
- testcases/rhsm/rhsm_gui/tc_ID272161_GUI_rhsm_gui_should_launch_although_CA_cert_invalid.py
name change for files I forgot to add GUI to.
> name change

- testcases/virt_who/esx/tc_ID289138_ESX_Datacenter_subpool_creation.py
- testcases/virt_who/virtwhobase.py
- testcases/virt_who/virtwhoconstants.py
add case tc_ID289138, for Datacenter
> add case tc_ID289138, for Datacenter

- testcases/rhsm/rhsm_gui/rhsmguibase.py
- testcases/rhsm/rhsm_gui/rhsmguilocator.py
- testcases/rhsm/rhsm_gui/tc_ID183421_GUI_list_consumed_entitlements_pool.py
- testcases/rhsm/rhsm_gui/tc_ID190646_GUI_my_installed_products_default_selection.py
- testcases/rhsm/rhsm_gui/tc_ID261838_GUI_smGUI_on_terminal_when_running_smGUI.py
- testcases/rhsm/rhsm_gui/tc_ID261955_GUI_smGUI_facts_update_after_registering.py
- testcases/rhsm/rhsm_gui/tc_ID262344_GUI_Service_Level,Type_should_be_displayed_properly.py
- testcases/rhsm/rhsm_gui/tc_ID272155_GUI_subscription_name_comma_should_not_be_and.py
one more set of new test cases
> one more batch of new testcases

- testcases/virt_who/esx/tc_ID289138_ESX_Datacenter_subpool_creation.py
- testcases/virt_who/esx/tc_ID289139_ESX_Datacenter_subpool_quantity_unlimited.py
- testcases/virt_who/esx/tc_ID289216_ESX_Datacenter_1_subscription_sufficient_to_guest.py
- testcases/virt_who/virtwhobase.py
- testcases/virt_who/virtwhoconstants.py
add tc_ID289139 and  tc_ID289216, update tc_ID289138
New function:
def check_consumed_status(self, sku_id, targetmachine_ip="")
def check_installed_status(self, targetmachine_ip="")
def setup_custom_facts(self, facts_key, facts_value, targetmachine_ip="")
def restore_facts(self, targetmachine_ip="")
> add tc_ID289139 and  tc_ID289216, update tc_ID289138

- testcases/rhsm/rhsm_gui/OOtool.py
object organizer tool for interpreter added
> object organizer tool for interpreter added

- testcases/virt_who/esx/tc_ID155173_ESX_check_uuid_when_guest_paused_or_shutdown.py
- testcases/virt_who/esx/tc_ID289216_ESX_Datacenter_1_subscription_sufficient_to_guest.py
- testcases/virt_who/kvm/tc_ID289216_Datacenter_1_subscription_sufficient_to_guest.py
- testcases/virt_who/kvm/tc_ID301085_Instance_compliance_in_guest_regardless_sockets_RAM_cores.py
- testcases/virt_who/kvm/tc_ID301521_Instance_host_consume_increments_instance_multiplier.py
- testcases/virt_who/virtwhobase.py
add check_consumed_status() to check the consumed lines value
add check_installed_status() to check the installed lines value
> enhancement check_consumed_status() and check_installed_status()

- testcases/rhsm/rhsm_gui/tc_ID115137_GUI_import_existing_certificates.py
- testcases/rhsm/rhsm_gui/tc_ID115155_GUI_register_using_proxy.py
- testcases/rhsm/rhsm_gui/tc_ID115175_GUI_subscribe_to_a_pool.py
- testcases/rhsm/rhsm_gui/tc_ID115179_GUI_unsubscribe_from_products.py
- testcases/rhsm/rhsm_gui/tc_ID115186_GUI_list_facts_info_of_curent_system_via_gui.py
- testcases/rhsm/rhsm_gui/tc_ID155109_GUI_list_avaialble_release.py
- testcases/rhsm/rhsm_gui/tc_ID178118_GUI_display_orgname_and_identity.py
- testcases/rhsm/rhsm_gui/tc_ID183421_GUI_list_consumed_entitlements_pool.py
- testcases/rhsm/rhsm_gui/tc_ID190646_GUI_my_installed_products_default_selection.py
- testcases/rhsm/rhsm_gui/tc_ID191583_GUI_filter_options_should_be_saved.py
- testcases/rhsm/rhsm_gui/tc_ID261838_GUI_smGUI_on_terminal_when_running_smGUI.py
- testcases/rhsm/rhsm_gui/tc_ID262134_GUI_launch_subscription_manager_gui_with_invalid_proxy_url.py
- testcases/rhsm/rhsm_gui/tc_ID262212_GUI_subscription_manager_gui_live_filter_should_not_crash.py
- testcases/rhsm/rhsm_gui/tc_ID262344_GUI_service_level_type_should_be_displayed_properly.py
- testcases/rhsm/rhsm_gui/tc_ID272155_GUI_subscription_name_comma_should_not_be_and.py
- testcases/rhsm/rhsm_gui/tc_ID272161_GUI_rhsm_gui_should_launch_although_CA_cert_invalid.py
- testcases/rhsm/rhsm_gui/tc_ID311028_GUI_proper_error_firstboot_when_invalid_activation_key.py
- testcases/rhsm/rhsm_gui/tc_ID324773_GUI_firstboot_appears_in_gui.py
- testcases/rhsm/rhsm_gui/tc_ID327127_GUI_option_to_register_with_proxy_firstboot.py
- testcases/rhsm/rhsmguibase.py
- testcases/rhsm/rhsmguilocator.py
style/bug fixes and 3 firstboot cases + documentation first draft
> style/bug fixes and 3 firstboot cases + documentation first draft

- testcases/virt_who/esx/tc_ID289221_ESX_Datacenter_guest_revoke_when_unregister_host.py
- testcases/virt_who/esx/tc_ID289675_ESX_Datacenter_repos_in_guest.py
- testcases/virt_who/virtwhobase.py
add func: check_cert_file() check ^Certificate: or ^Content: in cert file
add func: check_yum_repo() check ^Repo ID by subscription-manager repos --list
add case: tc_ID289221_ESX_Datacenter_guest_revoke_when_unregister_host.py
add case: tc_ID289675_ESX_Datacenter_repos_in_guest.py
> add case: tc_ID289221 and tc_ID289675

- testcases/virt_who/esx/tc_ID301083_ESX_Instance_one_instance_for_one_guest.py
- testcases/virt_who/esx/tc_ID301085_ESX_Instance_compliance_in_guest_regardless_sockets_RAM_cores.py
- testcases/virt_who/esx/tc_ID301527_ESX_Instance_compliance_in_guest.py
- testcases/virt_who/virtwhobase.py
add tc_ID301083, tc_ID301085, tc_ID301527
add func get_SKU_attribute(), return the attribute value by sku_id
> add tc_ID301083 and tc_ID301085

- testcases/rhsm/rhsm_gui/tc_ID115179_GUI_unsubscribe_from_products.py
- testcases/rhsm/rhsmguibase.py
> guibase update

- testcases/rhsm/rhsmguilocator.py
> locator debug

- Documentation-Ben
- testcases/rhsm/rhsmguibase.py
- testcases/rhsm/rhsmguilocator.py
> documenation + style changes

- testcases/rhsm/rhsm_gui/tc_ID190632_GUI_quit_subscription_manager_from_menu.py
- testcases/rhsm/rhsmguibase.py
> display bug fix and timer fix

- testcases/virt_who/esx/tc_ID174959_ESX_validate_mapping_info_after_re_register_host.py
- testcases/virt_who/esx/tc_ID248787_ESX_validate_limited_bonus_pool_creation.py
- testcases/virt_who/esx/tc_ID269395_ESX_Datacenter_guest_auto_attach_bonus_pool.py
- testcases/virt_who/virtwhobase.py
add case: tc_ID174959_ESX_validate_mapping_info_after_re_register_host.py
add case: tc_ID248787_ESX_validate_limited_bonus_pool_creation.py
add case: tc_ID269395_ESX_Datacenter_guest_auto_attach_bonus_pool.py
add func: sub_auto_subscribe() to auto subscribe pool
> add tc_ID174959, tc_ID248787, tc_ID269395

- testcases/virt_who/esx/tc_ID174959_ESX_validate_mapping_info_after_re_register_host.py
- testcases/virt_who/esx/tc_ID202506_ESX_execute_virtwho_b.py
- testcases/virt_who/esx/tc_ID202507_ESX_verify_virtwho_interval.py
- testcases/virt_who/esx/tc_ID214402_ESX_execute_virtwho_o.py
- testcases/virt_who/esx/tc_ID322864_ESX_check_log_after_add_guest.py
- testcases/virt_who/esx/tc_ID322866_ESX_run_virtwho_with_sam_option.py
- testcases/virt_who/esx/tc_ID327100_ESX_check_virtwho_3600s_interval.py
- testcases/virt_who/esx/tc_ID327394_ESX_killpid_restart_virtwho.py
- testcases/virt_who/virtwhobase.py
add vw_restart_virtwho_new() and vw_stop_virtwho_new()
> add vw_restart_virtwho_new() and vw_stop_virtwho_new()

- testcases/virt_who/esx/tc_ID202506_ESX_execute_virtwho_b.py
- testcases/virt_who/esx/tc_ID332956_ESX_list_consumed_after_virtwho_restart.py
add tc_ID332956, fix tc_ID202506
> add tc_ID332956, fix tc_ID202506

- testcases/rhsm/rhsm_gui/tc_ID190636_GUI_open_online_documentation_from_menu.py
- testcases/rhsm/rhsmguibase.py
> activate-window added + case

- testcases/rhsm/rhsmguibase.py
> removed activatewindow

- testcases/rhsm/rhsm_level_1/tc_ID115126_cleanlocaldata.py
- testcases/rhsm/rhsm_level_1/tc_ID141464_verify_consumer_deletion_from_server.py
- testcases/rhsm/rhsm_level_1/tc_ID143288_dryrun_bind_with_specified_SLA.py
- testcases/rhsm/rhsm_level_1/tc_ID147222_check_healing_attribute_of_consumer.py
> cmd line changes

- testcases/rhsm/rhsmguibase.py
> removed exist
